spring:
  application:
  name: PracticeReact

  datasource:
    url: jdbc:mysql://localhost:3306/ReactPractice?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1981
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or use `create`, `create-drop`, `validate`, or `none`
    show-sql: true
    properties:
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server:
  port: 8081