# ==========================
# Server Configuration
# ==========================
server.port=8081

# ==========================
# Hibernate / JPA Configuration
# ==========================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================
# H2 File-based DB (auto-create, keep data)
# ==========================
#spring.datasource.url=jdbc:h2:file:./data/kidsFunLearning;DB_CLOSE_DELAY=-1;MV_STORE=TRUE
spring.datasource.url=jdbc:h2:file:${user.home}/PracticeReactDB/kidsFunLearning;DB_CLOSE_DELAY=-1;MV_STORE=TRUE

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2

# ==========================
# H2 Console
# ==========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================
# Logging
# ==========================
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# suppress Spring Web debug logs keep it so not showing token in logger
logging.level.org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor=INFO

# ==========================
# Kafka Configuration
# ==========================
kafka.bootstrap-servers=localhost:9092
kafka.consumer.group-id=my-group
kafka.consumer.auto-offset-reset=earliest
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ==========================
# Security
# ==========================
spring.security.user.name=a
spring.security.user.password=a
spring.security.user.roles=ADMIN

# ======================
# Actuator
# ======================
management.endpoints.web.exposure.include=health,info,metrics,mappings,loggers,threaddump
management.server.port=8081
management.endpoints.web.base-path=/waw

